### PR TITLE
[Feature #159082388] Add Search Functionality with custom filters

### PR DESCRIPTION
**Pull request by lytes20**
#### What does this PR do?
- Adds Search Functionality with custom filters
#### Description of Task to be completed?
- A user is able to search for an article by author, article title and tag.
#### How should this be manually tested?
- By performing a search on articles using these search URLs
- Example:
- `api/articles/search?tag=AngularJS`
- `api/articles/search?author=joseph`
- `api/articles/search?title=How to kill a dragon`
#### Any background context you want to provide?
- Looking for article(s) in their dozens can be daunting. It would be easier if we had a search functionality with custom filters. These filters avail the members to create a search criterion of their own which helps them to narrow it down if they don’t know the title exactly.
#### What are the relevant pivotal tracker stories?
[159082388](https://www.pivotaltracker.com/story/show/159082388)
#### Screenshots
screen shot 2018-08-16 at 17 39 12
screen shot 2018-08-16 at 17 41 25
screen shot 2018-08-16 at 18 16 52

#### Questions:

### CODE REVIEW

**Review by ssewilliam — APPROVED** [review]
@lytes20 
Nice work 
- Have you also checked out encoded URLs for spaces between fields

**Review by abulojoshua1 — APPROVED** [review]

**Comment by lytes20** [comment]
@ssewilliam the space issue in the title has been resolved

**Review by ssewilliam — COMMENTED** [review]
@lytes20 
This looks better.
- Can we also do filter by favourited

**Comment by lytes20** [comment]
Yes as I guess we can do that @ssewilliam but I think we can skip it for now as time is not on our best friend right now

**Pull request merged**
