### PR TITLE
#159082370 Integrate TravisCI with readme badge

### PR DESCRIPTION
**Pull request by lytes20**
#### What does this PR do?
- Add TravisCI badge to the readme plus the coverage and code climate maintainability badges
#### Description of Task to be completed?
- This is required to automatically run tests and other preliminary build steps required to ship the next iteration of the product
#### How should this be manually tested?
- By making a change to the code and pushing it to the repository
#### Any background context you want to provide?
- Right now all the badges point to develop, this PR need needs to be merged to trigger a build on develop
#### What are the relevant pivotal tracker stories?
[#159082370](https://www.pivotaltracker.com/story/show/159082370)
#### Screenshots
screen shot 2018-07-27 at 10 08 44

#### Questions:
No questions but i wait all of your feedback on this

### CODE REVIEW

**Comment by ssewilliam** [comment]
I see this looks ok
But how long does it take to have the badges showing up **statuses**

**Comment by geofrocker** [comment]
@lytes20 The build should be passing and the badge should show the coverage percentage

**Comment by abulojoshua1** [comment]
Looks good. Just think badges are taking a bit longer to pass. But all should be well soon.

**Comment by lytes20** [comment]
@ssewilliam @geofrocker @abulojoshua1 right now the TravisCI and coverage badges are pointing to develop, the PR needs to first be merged to develop for them to show status and percentage respectively. The current builds on Travis are on this branch (ch-travisci-badge-159082370) containing the badges, the `travis.yml` file, and the `coveralls.yml file`.

**Comment by lytes20** [comment]
If you have another way i can approach this am all ears. Beacuse If i make the badges point to this branch on the read me, i will again have to edit the read me even after the merge.

**Comment by geofrocker** [comment]
Makes sense

**Pull request merged**
